In [1]:
# for loading the pre-trained models
from cryspnet.models import *
# for feature generation and plotting
from cryspnet.utils import *
# for accessing some pre-defined constant
from cryspnet.config import *

In [2]:
import pandas as pd
import numpy as np

# Load in the Pre-Trained Models 

These three API helps you to retrieved them
```Python
    load_Bravais_models(n_ensembler, which)
    load_Lattice_models()
    load_SpaceGroup_models()
```

**Note**: If the file cannot be found error showed, make sure your follow the instruction to download and extract those models to the correct place.

In [3]:
BE = load_Bravais_models(n_ensembler=5, which="whole")

In [4]:
LB = load_Lattice_models()

In [5]:
SGB = load_SpaceGroup_models()

# Download the Superhard Dataset

Matminer provide an easy to access API for fast dataset retrieval. Check out [this page](https://hackingmaterials.lbl.gov/matminer/dataset_summary.html) for datasets that are all available

In [6]:
from matminer.datasets import load_dataset

In [7]:
shard = load_dataset("brgoch_superhard_training")

In [8]:
shard.head()

formula  bulk_modulus  shear_modulus composition material_id  \
0   AlPt3    225.230461      91.197748    (Al, Pt)      mp-188   
1   Mn2Nb    232.696340      74.590157    (Mn, Nb)    mp-12659   
2    HfO2    204.573433      98.564374     (Hf, O)      mp-352   
3   Cu3Pt    159.312640      51.778816    (Cu, Pt)    mp-12086   
4   Mg3Pt     69.637565      27.588765    (Mg, Pt)    mp-18707   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 structure  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     [[0. 0. 0.] Al, [0.         1.96140395 1.96140395] Pt, [1.96140395 1.96140395 0.        ] Pt, [1.96140395 0.         1.96140395] Pt]   
1                                                                                                                [[-2.23765223e-08  1.42974191e+00  5.92614104e+00] Mn, [3.57977169 0.71487093 1.97538035] Mn, [1.23819283 0.71487093 1.97538035] Mn, [1.17078941 3.45760869 5.92614104] Mn, [0. 0. 0.] Mn, [0.        0.        3.9507607] Mn, [2.40898226 2.74273771 1.97538035] Mn, [-1.17078945  3.45760869  5.92614104] Mn, [-2.07564892e-08  2.78165309e+00  3.46044846e+00] Nb, [2.40898226 1.39082653 7.41120915] Nb, [2.40898226 1.39082653 4.44107293] Nb, [-2.07564892e-08  2.78165309e+00  4.90312238e-01] Nb]   
2                                                                                                                                          [[2.24450185 3.85793022 4.83390736] O, [2.77883096 1.26035638 2.32337921] O, [ 2.79593023  1.33721745 -0.3395849 ] O, [2.26160112 3.93479129 2.17094325] O, [0.33243749 1.71503186 1.79217508] O, [4.72509386 4.3126057  0.03918327] O, [4.70799459 3.48011581 2.70214738] O, [0.31533822 0.88254197 4.45513919] O, [1.37618055 2.37584161 3.54068723] Hf, [3.64715226 4.97341544 3.61659934] Hf, [3.66425153 2.81930606 0.95363523] Hf, [1.39327982 0.22173223 0.87772312] Hf]   
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     [[0.         1.86144248 1.86144248] Cu, [1.86144248 1.86144248 0.        ] Cu, [1.86144248 0.         1.86144248] Cu, [0. 0. 0.] Pt]   
4  [[0.         0.         2.73626461] Mg, [0.         0.         6.95125305] Mg, [-3.97440991e-08  4.58925330e+00  1.79637294e+00] Mg, [3.97440996 2.29462661 6.01136137] Mg, [-3.97440991e-08  4.58925330e+00  6.01136137e+00] Mg, [3.97440996 2.29462661 1.79637294] Mg, [1.12369616 1.94629885 0.72058152] Mg, [-1.12369616  1.94629885  4.93556996] Mg, [2.24739233 0.         4.93556996] Mg, [5.70142751 0.         0.72058152] Mg, [-2.85071376  4.93758106  0.72058152] Mg, [2.85071376 4.93758106 4.93556996] Mg, [1.48939724 2.57971169 3.61780896] Mg, [-1.48939724  2.57971169  7.

# Generate Predictors

In [9]:
FG = FeatureGenerator()

In [10]:
predictors = FG.generate(shard[['formula']])

StrToComposition:   0%|          | 0/2574 [00:00<?, ?it/s]

MultipleFeaturizer:   0%|          | 0/2574 [00:00<?, ?it/s]

# Prediction-High Level API

Utilize the library is simple, every model has a **.predicts()** method that take a dataframe with ***predictors*** as input and output ***Bravais Lattices***, ***space group numbers*** or ***Lattice parameters***. 

## Bravais Lattice

Prediction from ***Bravais Lattice Models*** has two parts in the output: First one is the ***top-n highest probability in the prediction***. Second one is ***the classes that associated with those in the first one***. The top-n is controlled by the parameter **topn_bravais**. The first column of 

In [11]:
# first one is the probability of the top-N prediction
# second one is the predicted top-N Bravais Lattice
Bravais_probs, Bravais = BE.predicts(predictors, topn_bravais=2)

/home/aurora/cryspnet/cryspnet/models.py:255: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  return preds[auxidxs, idxs], self.classes[idxs]


### Example-Bravais Lattice Prediction

The probability is order from left to right meaning the highest one are always on the left.

In [12]:
Bravais_probs[:2]

array([[9.9996740e-01, 2.2746925e-05],
       [4.1430849e-01, 2.8673396e-01]], dtype=float32)

Here is the corresponding Bravais Lattice

In [13]:
Bravais[:2]

array([['orthorhombic (P)', 'monoclinic (C)'],
       ['rhombohedral (P)', 'hexagonal (P)']], dtype=object)

## Lattice Parameter and Space Group

To use those two model, a column with the name **Bravais** must exists in the input predictors dataframe.
<br/>This information could be obtained from previous predictions or experimental data.

In [14]:
lattices = []
spacegroups = []
for i in range(0, 2):
    predictors['Bravais'] = Bravais[:, i]
    lattice = LB.predicts(predictors)
    lattices.append(lattice)
    
    spacegroup = SGB.predicts(predictors)
    spacegroups.append(spacegroup)

/home/aurora/cryspnet/cryspnet/models.py:200: RuntimeWarning: overflow encountered in exp
  return np.exp(preds)
/home/aurora/anaconda3/envs/cryspnetv2/lib/python3.8/site-packages/pandas/core/arraylike.py:274: RuntimeWarning: invalid value encountered in sin
  result = getattr(ufunc, method)(*inputs, **kwargs)
/home/aurora/anaconda3/envs/cryspnetv2/lib/python3.8/site-packages/pandas/core/arraylike.py:274: RuntimeWarning: invalid value encountered in cos
  result = getattr(ufunc, method)(*inputs, **kwargs)


### Example-Lattice Parameter Prediction 
***Lattice Parameter Model*** would output a ***dataframe*** contains columns: ***a***, ***b***, ***c***, ***α***, ***β***,and ***γ***

In [15]:
lattices[0].head()

a         b         c  alpha  beta  gamma           v
0  7.418073  9.941552  6.821741   90.0  90.0   90.0  503.084013
1  0.000000  0.000000  0.000000    0.0   0.0    0.0    0.000000
2  7.814845  7.814845  7.814845   90.0  90.0   90.0  477.266677
3  8.261739  8.261739  8.261739   90.0  90.0   90.0  563.915990
4  7.447362  9.912762  6.669214   90.0  90.0   90.0  492.347582

### Example-Space Group Prediction
***Space Group Model*** would output ***top-n probability*** and corresponding ***space group number***
in similar manner as Bravais Lattice Model

In [16]:
# top-N probability, top-N space group number
spacegroup_probs, spacegroup = spacegroups[0]

In [17]:
spacegroup_probs[:5]

array([[9.55480874e-01, 4.43613380e-02, 1.57732997e-04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.59777439e-01, 3.83206278e-01, 5.70162982e-02],
       [9.72254515e-01, 2.10020747e-02, 6.15153601e-03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [18]:
spacegroup[:5]

array([[ 74.,  62.,  61.],
       [148., 167., 166.],
       [225., 227., 216.],
       [220., 204., 229.],
       [ 62.,  74.,  61.]])

## Low Level API

### Load dataset to the model

All models contain **.load()** method to attach the dataset to the model. The model then would perform pre-processing on the input dataset. 

In [19]:
BE.load(predictors)
LB.load(predictors) # note we have "Bravais" in this dataframe already
SGB.load(predictors)

### Get the Raw Prediction
Sometimes, processing raw prediction is easy for further analysis. Make sure you load in dataset to the models before running lines in below.

The raw prediction is stored in the form of **torch tensor**. Prediction is stored in different format that is specified to each models. 

#### Bravais Lattice Model

For Bravais Lattice Model, raw prediction contains output from **N** (defined by user) models. i.e. the shape of the tensor is (N, dataset_size, 14)

In [20]:
preds = BE.get_preds()

In [21]:
preds.shape

torch.Size([5, 2574, 14])

The Bravais Lattice map to the predicted probability is stored in **.classes**

In [22]:
BE.classes

Index(['cubic (I)', 'cubic (F)', 'cubic (P)', 'hexagonal (P)',
       'rhombohedral (P)', 'tetragonal (I)', 'tetragonal (P)',
       'orthorhombic (I)', 'orthorhombic (F)', 'orthorhombic (C)',
       'orthorhombic (P)', 'monoclinic (C)', 'monoclinic (P)',
       'triclinic (P)'],
      dtype='object')

#### Space Group Model and Lattice Parameter Model

For Space Group Model and Lattice Parameter Model, the raw prediction is a dictionary containing prediction from different sub-models. The key of the dictionary shows which sub-models the prediction comes from.

In [23]:
preds = SGB.get_preds()

In [24]:
preds.keys()

dict_keys(['cubic (I)', 'cubic (F)', 'cubic (P)', 'hexagonal (P)', 'rhombohedral (P)', 'tetragonal (I)', 'tetragonal (P)', 'orthorhombic (I)', 'orthorhombic (F)', 'orthorhombic (C)', 'orthorhombic (P)', 'monoclinic (C)', 'monoclinic (P)', 'triclinic (P)'])

In [25]:
preds['cubic (F)'][:3,]

tensor([[0.0000e+00, 1.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0000e+00, 0.0000e+00],
        [5.0087e-05, 2.6173e-01, 7.3822e-01]])

The space group number for each sub model prediction is little more complicated. All submodels is stored in the **.Ps** field. For each sub-model access classes is similar to Bravais Lattice one. Here is an example of getting the classes for cubic (F) sub-model

In [27]:
SGB.Ms['cubic (F)'].classes

array([216, 225, 227])

In [28]:
preds = LB.get_preds()

In [29]:
preds.keys()

dict_keys(['cubic (I)', 'cubic (F)', 'cubic (P)', 'hexagonal (P)', 'rhombohedral (P)', 'tetragonal (I)', 'tetragonal (P)', 'orthorhombic (I)', 'orthorhombic (F)', 'orthorhombic (C)', 'orthorhombic (P)', 'monoclinic (C)', 'monoclinic (P)', 'triclinic (P)'])

In [30]:
preds['triclinic (P)'][:3]

tensor([[-9.8452e+07, -8.6062e+07, -8.4030e+07,  4.0698e+06,  1.3044e+07,
          2.9655e+07],
        [-5.2221e-01,  1.4229e-01, -5.3990e-01, -5.9890e-02, -1.5190e-01,
          2.1077e-01],
        [ 2.2412e+06, -2.8403e+07, -2.1658e+07,  1.8027e+07,  1.4471e+07,
          2.2346e+07]])

The **PRED_COLS** constant defined *config.py* tells you which lattice parameters the sub model is predicting.  

In [31]:
PRED_COLS

{'cubic (P)': ['a'],
 'cubic (F)': ['a'],
 'cubic (I)': ['a'],
 'monoclinic (P)': ['a', 'b', 'c', 'beta'],
 'monoclinic (C)': ['a', 'b', 'c', 'beta'],
 'hexagonal (P)': ['a', 'c'],
 'rhombohedral (P)': ['a', 'alpha'],
 'tetragonal (P)': ['a', 'c'],
 'tetragonal (I)': ['a', 'c'],
 'orthorhombic (P)': ['a', 'b', 'c'],
 'orthorhombic (C)': ['a', 'b', 'c'],
 'orthorhombic (F)': ['a', 'b', 'c'],
 'orthorhombic (I)': ['a', 'b', 'c'],
 'triclinic (P)': ['a', 'b', 'c', 'alpha', 'beta', 'gamma']}